version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    ports: 
      - ${MDB_PORT}:3306
    environment:
      #- BITNAMI_DEBUG=true
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=db_user
      - MARIADB_DATABASE=docker_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './mariadb:/bitnami/mariadb'
      #- './init-db:/docker-entrypoint-initdb.d'
  moodle:
    image: 'docker.io/bitnami/moodle:3.10.1'
    ports:
      - '${MDL_HTTP_PORT}:8080'
      - '${MDL_HTTPS_PORT}:8443'
    environment:
      #- BITNAMI_DEBUG=true
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=db_user
      - MOODLE_DATABASE_NAME=docker_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle:/bitnami/moodle'
      - './moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: '' 
    depends_on:
      - mariadb